---
version: '3'

services:
  kitchen-sensor:
    image: jcostom/sensorem:latest
    container_name: kitchen-sensor
    restart: unless-stopped
    environment:
      TZ: America/New_York
      APIKEY: <my-switchbot-api-key>
      DEVID: <my-switchbot-device-id>
      SLEEPTIME: 300
      INFLUX_BUCKET: <my-InfluxDB-2.x-Bucket-Name>
      INFLUX_ORG: <my-InfluxDB-2.x-Org-Name>
      INFLUX_TOKEN: <my-InfluxDB-2.x-Token>
      INFLUX_URL: 'http://<my-influxDB-server:8086/'
      INFLUX_MEASUREMENT_NAME: kitchen
    network_mode: bridge
