name: build our image

on:
  push:
    branches: 
      - 'main'
    tags:
      - '*.*'
      - '*.*.*'

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with: 
          platforms: all
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=pep440,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
